### PR TITLE
Fixed #66

### LINKED ISSUE #66: chrome.storage.local.get === chrome.storage.sync.get
```js
const chrome = require( 'sinon-chrome' );
const chai = require( 'chai' );
chai.use( require( 'sinon-chai' ) );
const expect = chai.expect;

expect( chrome.storage.sync.get ).not.to.equal( chrome.storage.local.get ); // fails, these are equal

expect( chrome.storage.sync.get ).not.to.have.been.called;
expect( chrome.storage.local.get ).not.to.have.been.called;
chrome.storage.sync.get( 'test' );
expect( chrome.storage.sync.get ).to.have.been.called;
expect( chrome.storage.local.get ).not.to.have.been.called; // fails
```

I found this after hours of trying to figure out why my test was failing where I was testing that my extension loads from sync storage and not from local storage.

### PR DESCRIPTION
**Pull request by crimx**
Every property should get a fresh type instance.

### CODE REVIEW

**Comment by acvetkov** [comment]
@crimx, great job!

**Comment by acvetkov** [comment]
I've published new version 2.2.2
https://www.npmjs.com/package/sinon-chrome

**Comment by crimx** [comment]
Hey @acvetkov , the build is not correct. The code in `./out` is still the old one.

**Comment by crimx** [comment]
Never mind. Looks like it's Yarn's problem. NPM resolves the right package.

**Comment by crimx** [comment]
Nope :joy: the NPM package is still not correct. './out/api/index.js` got

```js
var instance = new TypeClass(this.stubs, this.events, this.props, namespace);
```

@acvetkov maybe you can take a look and perhaps publish another build?

**Comment by acvetkov** [comment]
> the NPM package is still not correct. './out/api/index.js` got

it's so sad

**Pull request merged**
